export type PaymentData = {
  id: number;
  transactionId: string;
  transactionNote: string;

  parentName: string;
  playerName: string;

  session: string;

  amount: number;
  methodType: "Booking" | "Manual";
  methodDetail: string;

  date: string;
  time: string;

  status: "Completed" | "Pending" | "Failed" | "Comped" | "Voided";
};


export const PAYMENT_DATA: PaymentData[] = [
  {
    id: 1,
    transactionId: "SQ-20251203-001",
    transactionNote: "Duplicate checked",
    parentName: "Sarah Johnson",
    playerName: "Emma Johnson",
    session: "Advanced Basketball Training",
    amount: 120,
    methodType: "Booking",
    methodDetail: "Mastercard •••• 5555",
    date: "12/03/2025",
    time: "03:15 PM",
    status: "Pending",
  },
  {
    id: 2,
    transactionId: "SQ-20251203-002",
    transactionNote: "Duplicate checked",
    parentName: "Michael Brown",
    playerName: "Lucas Brown",
    session: "Swimming Basics",
    amount: 90,
    methodType: "Booking",
    methodDetail: "Visa •••• 4421",
    date: "12/03/2025",
    time: "11:40 AM",
    status: "Completed",
  },
  {
    id: 3,
    transactionId: "SQ-20251204-003",
    transactionNote: "Duplicate checked",
    parentName: "Ayesha Khan",
    playerName: "Ali Khan",
    session: "Football Conditioning",
    amount: 150,
    methodType: "Manual",
    methodDetail: "Cash",
    date: "12/04/2025",
    time: "09:20 AM",
    status: "Pending",
  },
  {
    id: 4,
    transactionId: "SQ-20251204-004",
    transactionNote: "Duplicate checked",
    parentName: "David Wilson",
    playerName: "Oliver Wilson",
    session: "Tennis Pro Training",
    amount: 200,
    methodType: "Booking",
    methodDetail: "Visa •••• 8890",
    date: "12/04/2025",
    time: "05:55 PM",
    status: "Failed",
  },
  {
    id: 5,
    transactionId: "SQ-20251205-005",
    transactionNote: "Duplicate checked",
    parentName: "Fatima Noor",
    playerName: "Hassan Noor",
    session: "Swimming Advanced",
    amount: 0,
    methodType: "Manual",
    methodDetail: "Comped",
    date: "12/05/2025",
    time: "02:10 PM",
    status: "Comped",
  },
  {
    id: 6,
    transactionId: "SQ-20251205-006",
    transactionNote: "Duplicate checked",
    parentName: "John Smith",
    playerName: "Ethan Smith",
    session: "Basketball Drills",
    amount: 110,
    methodType: "Booking",
    methodDetail: "Mastercard •••• 3322",
    date: "12/05/2025",
    time: "06:30 PM",
    status: "Voided",
  },
  {
    id: 7,
    transactionId: "SQ-20251206-007",
    transactionNote: "Duplicate checked",
    parentName: "Sana Ahmed",
    playerName: "Zain Ahmed",
    session: "Cricket Nets",
    amount: 75,
    methodType: "Booking",
    methodDetail: "Visa •••• 9981",
    date: "12/06/2025",
    time: "10:00 AM",
    status: "Completed",
  },
  {
    id: 8,
    transactionId: "SQ-20251206-008",
    transactionNote: "Duplicate checked",
    parentName: "Robert Lee",
    playerName: "Kevin Lee",
    session: "Badminton Training",
    amount: 60,
    methodType: "Manual",
    methodDetail: "Bank Transfer",
    date: "12/06/2025",
    time: "01:45 PM",
    status: "Pending",
  },
  {
    id: 9,
    transactionId: "SQ-20251207-009",
    transactionNote: "Duplicate checked",
    parentName: "Mary Collins",
    playerName: "Sophie Collins",
    session: "Gymnastics",
    amount: 130,
    methodType: "Booking",
    methodDetail: "Visa •••• 1133",
    date: "12/07/2025",
    time: "04:05 PM",
    status: "Failed",
  },
  {
    id: 10,
    transactionId: "SQ-20251207-010",
    transactionNote: "Duplicate checked",
    parentName: "Bilal Raza",
    playerName: "Hamza Raza",
    session: "Karate Training",
    amount: 0,
    methodType: "Manual",
    methodDetail: "Comped",
    date: "12/07/2025",
    time: "07:20 PM",
    status: "Comped",
  },
  {
    id: 11,
    transactionId: "SQ-20251208-011",
    transactionNote: "Duplicate checked",
    parentName: "Linda Green",
    playerName: "Chloe Green",
    session: "Yoga for Athletes",
    amount: 85,
    methodType: "Booking",
    methodDetail: "Mastercard •••• 7777",
    date: "12/08/2025",
    time: "08:30 AM",
    status: "Completed",
  },
  {
    id: 12,
    transactionId: "SQ-20251208-012",
    transactionNote: "Duplicate checked",
    parentName: "Omar Farooq",
    playerName: "Ibrahim Farooq",
    session: "Strength Training",
    amount: 140,
    methodType: "Booking",
    methodDetail: "Visa •••• 2211",
    date: "12/08/2025",
    time: "06:10 PM",
    status: "Voided",
  },
];
