export interface SessionDataType {
  id: string;
  sessionName: string;
  type: string;
  date: string;
  time: string;
  coachName: string;
  playerName: string;
  price: string;
  payment: string;
  status: string;
  max_players?: number;
  location?: string;
}

export const SESSIONS_DATA: SessionDataType[] = [
  {
    id: "1",
    sessionName: "Beginner Skills Training",
    type: "Group",
    date: "Jan 05, 2026",
    time: "4:00 PM",
    coachName: "Coach Martinez",
    playerName: "Liam Johnson",
    price: "$10",
    payment: "Paid",
    status: "Upcoming",
  },
  {
    id: "2",
    sessionName: "Ball Control Basics",
    type: "Group",
    date: "Jan 06, 2026",
    time: "5:00 PM",
    coachName: "Coach Martinez",
    playerName: "Noah Williams",
    price: "$12",
    payment: "Pending",
    status: "Upcoming",
  },
  {
    id: "3",
    sessionName: "Speed & Agility",
    type: "Group",
    date: "Jan 07, 2026",
    time: "6:00 PM",
    coachName: "Coach Martinez",
    playerName: "Ethan Brown",
    price: "$8",
    payment: "Partial",
    status: "Completed",
  },
  {
    id: "4",
    sessionName: "Goal Scoring Practice",
    type: "Private",
    date: "Jan 08, 2026",
    time: "7:00 PM",
    coachName: "Coach Martinez",
    playerName: "Oliver Davis",
    price: "$15",
    payment: "Comped",
    status: "Completed",
  },
  {
    id: "5",
    sessionName: "Fitness Conditioning",
    type: "Group",
    date: "Jan 09, 2026",
    time: "3:30 PM",
    coachName: "Coach Martinez",
    playerName: "James Wilson",
    price: "$10",
    payment: "Paid",
    status: "Cancelled",
  },
  {
    id: "6",
    sessionName: "Dribbling Drills",
    type: "Group",
    date: "Jan 10, 2026",
    time: "4:30 PM",
    coachName: "Coach Martinez",
    playerName: "Benjamin Moore",
    price: "$9",
    payment: "Paid",
    status: "Upcoming",
  },
  {
    id: "7",
    sessionName: "Passing Accuracy",
    type: "Group",
    date: "Jan 11, 2026",
    time: "5:30 PM",
    coachName: "Coach Martinez",
    playerName: "Lucas Taylor",
    price: "$11",
    payment: "Pending",
    status: "Upcoming",
  },
  {
    id: "8",
    sessionName: "Defensive Positioning",
    type: "Group",
    date: "Jan 12, 2026",
    time: "6:00 PM",
    coachName: "Coach Martinez",
    playerName: "Henry Anderson",
    price: "$10",
    payment: "Paid",
    status: "Completed",
  },
  {
    id: "9",
    sessionName: "One on One Training",
    type: "Private",
    date: "Jan 13, 2026",
    time: "7:30 PM",
    coachName: "Coach Martinez",
    playerName: "Alexander Thomas",
    price: "$18",
    payment: "Partial",
    status: "Upcoming",
  },
  {
    id: "10",
    sessionName: "Shooting Technique",
    type: "Group",
    date: "Jan 14, 2026",
    time: "4:00 PM",
    coachName: "Coach Martinez",
    playerName: "Mason Jackson",
    price: "$12",
    payment: "Paid",
    status: "Completed",
  },
  {
    id: "11",
    sessionName: "Warm Up Drills",
    type: "Group",
    date: "Jan 15, 2026",
    time: "3:00 PM",
    coachName: "Coach Martinez",
    playerName: "Logan White",
    price: "$7",
    payment: "Paid",
    status: "Completed",
  },
  {
    id: "12",
    sessionName: "Core Strength",
    type: "Group",
    date: "Jan 16, 2026",
    time: "5:00 PM",
    coachName: "Coach Martinez",
    playerName: "Daniel Harris",
    price: "$9",
    payment: "Pending",
    status: "Upcoming",
  },
  {
    id: "13",
    sessionName: "Match Preparation",
    type: "Group",
    date: "Jan 17, 2026",
    time: "6:30 PM",
    coachName: "Coach Martinez",
    playerName: "Matthew Martin",
    price: "$11",
    payment: "Paid",
    status: "Upcoming",
  },
  {
    id: "14",
    sessionName: "Footwork Training",
    type: "Group",
    date: "Jan 18, 2026",
    time: "4:30 PM",
    coachName: "Coach Martinez",
    playerName: "Sebastian Lee",
    price: "$10",
    payment: "Comped",
    status: "Completed",
  },
  {
    id: "15",
    sessionName: "Endurance Session",
    type: "Group",
    date: "Jan 19, 2026",
    time: "5:30 PM",
    coachName: "Coach Martinez",
    playerName: "Jack Walker",
    price: "$8",
    payment: "Paid",
    status: "Upcoming",
  },
  {
    id: "16",
    sessionName: "Tactical Awareness",
    type: "Group",
    date: "Jan 20, 2026",
    time: "6:00 PM",
    coachName: "Coach Martinez",
    playerName: "Owen Hall",
    price: "$12",
    payment: "Pending",
    status: "Upcoming",
  },
  {
    id: "17",
    sessionName: "Recovery Stretching",
    type: "Group",
    date: "Jan 21, 2026",
    time: "3:30 PM",
    coachName: "Coach Martinez",
    playerName: "Samuel Allen",
    price: "$6",
    payment: "Paid",
    status: "Completed",
  },
  {
    id: "18",
    sessionName: "Attacking Movement",
    type: "Group",
    date: "Jan 22, 2026",
    time: "5:00 PM",
    coachName: "Coach Martinez",
    playerName: "Joseph Young",
    price: "$11",
    payment: "Partial",
    status: "Upcoming",
  },
  {
    id: "19",
    sessionName: "Defensive Drills",
    type: "Group",
    date: "Jan 23, 2026",
    time: "6:00 PM",
    coachName: "Coach Martinez",
    playerName: "David King",
    price: "$10",
    payment: "Paid",
    status: "Completed",
  },
  {
    id: "20",
    sessionName: "Skills Assessment",
    type: "Private",
    date: "Jan 24, 2026",
    time: "7:00 PM",
    coachName: "Coach Martinez",
    playerName: "Ryan Scott",
    price: "$15",
    payment: "Pending",
    status: "Upcoming",
  },
];

